branches:
  only:
  - master
  - "/^wagon-git-[\\d\\.]+$/"
language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  apt:
    packages:
    - graphviz
  sonarqube: true
env:
  global:
  - secure: aagYTtHOrY7nBp4NKdQz9NcYK9zfJ4faTUGwS7DwYuDPsc1qJiW3n5AFlnWAxWm4i9S1EX20evpU0LraU4tMre9uQ+jsiflEbBNEJkzsy+ZbPz3WS9pNWWiSju5Ed6DIZa5s5iisollYspuyx9DBCfSWxYEUGRSQDfXR77bxhJU=
  - secure: K5TtEWOkHgCHpFxhzWlEuwn/JsE4jxrnwrUJ7fwog/vERFFUI8nJ7lP51iaTe0lkBHQjYDjYedKYA0xcloHVyF5/zmEP2HyMolV6uHunf23GJ1t8UYHOlZcbWFoTr+7p6S8LFsld3nMdcD4e5LR1TKFmrffoITqy/PaaKfQ7UvI=
before_install:
- openssl aes-256-cbc -K $encrypted_ec7f27486862_key -iv $encrypted_ec7f27486862_iv
  -in deploy-keys.tar.enc -out deploy-keys.tar -d
install:
- tar xf deploy-keys.tar -C $HOME && chmod go-rwx -R $HOME/.m2 $HOME/.ssh
- mvn dependency:go-offline
before_script:
- mvn clean
script:
- mvn verify site
after_success:
- mvn sonar:sonar
deploy:
- provider: script
  skip_cleanup: true
  script: mvn deploy site-deploy
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: printf 'scm.tag=%1s\nscm.url=scm:git:https://git@github.com/%2s.git' "${TRAVIS_TAG}"
    "${TRAVIS_REPO_SLUG}" > release.properties && mvn release:perform
  on:
    tags: true
